ENV = {'PATH': '/usr/local/bin:/opt/bin:/bin:/usr/bin:/snap/bin', 'LD_LIBRARY_PATH': '', 'MPICH_CC': 'gcc', 'MPICH_CLINKER': 'gcc', 'HOME': '/home/liguolong', 'MPICH_CXX': 'g++'}
RSFROOT = '/mnt/e/small_mada/madagascar-4.2'
AR = 'ar'
HAVE_RPC = True
JPEG = 'jpeg'
OPENGL = ['GL', 'GLU', 'glut']
OPENGLFLAGS = None
OPENGLPATH = None
MPICC = '/usr/bin/mpicc'
MPICXX = '/usr/bin/mpicxx'
MPIRUN = '/usr/bin/mpirun'
SPARSEPATH = ['/usr/include/suitesparse']
SPARSELIBS = ['umfpack', 'cholmod', 'amd', 'camd', 'colamd', 'ccolamd']
FFTW = 'fftw3f'
DFFTW = 'fftw3'
FFTWOMP = 'fftw3f_threads'
DFFTWOMP = 'fftw3_threads'
OMP = True
PTHREADS = True
BLAS = 'blas'
LAPACK = ['lapack', 'blas']
PPM = 'netpbm'
TIFF = 'tiff'
GD = 'gd'
GIFANIM = True
PLPLOT = 'plplot'
PLPLOTPATH = '/usr/include/plplot'
PLPLOTLIBPATH = None
FFMPEG = 'avcodec avutil'
FFMPEGPATH = '/usr/include/x86_64-linux-gnu/libavcodec'
CAIROPNG = 'cairo'
CAIROSVG = 'cairo'
CAIROPDF = 'cairo'
CAIROPATH = '/usr/include/cairo'
PPMPATH = '/usr/include/netpbm'
SFPEN = 'xtpen'
DYNLIB = ''
CC = 'gcc'
CFLAGS = '-O2 -x c -std=gnu17 -Wall -pedantic -fopenmp'
CPPPATH = ['/usr/include/tirpc']
LIBPATH = []
LIBS = ['m', 'tirpc', 'blas', 'lapack', 'blas', 'gomp', 'fftw3f', 'fftw3', 'fftw3f_threads', 'fftw3_threads']
LINKFLAGS = ['-pthread', '-fopenmp']
XLIBPATH = ['/usr/lib/X11']
XLIBS = ['Xaw', 'Xt', 'X11']
XINC = ['/usr/include']
API = ['c++']
CXX = 'g++'
CXXFLAGS = '-O2 -std=gnu++17 -U__STRICT_ANSI__ -Wall -pedantic -fopenmp'
F77 = 'gfortran'
FORTRAN = 'gfortran'
F90 = 'gfortran'
F90FLAGS = '-O2 -fopenmp'
JAVAC = 'javac'
CUDA_TOOLKIT_PATH = None
NUMPY = True
SWIG = '/usr/bin/swig'
