.TH sfai2refl 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfai2refl \- Convert acoustic impedance to reflectivity. \n.SH SYNOPSIS
.B sfai2refl < ai.rsf > mod.rsf
.SH COMMENTS

August 2013 program of the month:
http://www.ahay.org/blog/2013/08/02/program-of-the-month-sfai2refl/

.SH SOURCE
.I system/seismic/Mai2refl.c
.SH VERSION
4.2
