.TH sfaliasp 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfaliasp \- Aliasing test. \n.SH SYNOPSIS
.B sfaliasp > out.rsf n1=600 n2=24 cycles=10. ix0=0 slow=0.1
.SH PARAMETERS
.PD 0
.TP
.I float  
.B cycles
.B =10.
.R  	wave frequency
.TP
.I int    
.B ix0
.B =0
.R  	central trace
.TP
.I int    
.B n1
.B =600
.R  
.TP
.I int    
.B n2
.B =24
.R  	dimensions
.TP
.I float  
.B slow
.B =0.1
.R  	slowness
.SH SOURCE
.I system/generic/Maliasp.c
.SH VERSION
4.2
