.TH sfcascade 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfcascade \- Velocity partitioning for cascaded migrations. \n.SH SYNOPSIS
.B sfcascade < in.rsf > out.rsf ntcut= tcut= ncut=1
.SH PARAMETERS
.PD 0
.TP
.I int    
.B ncut
.B =1
.R  	number of cuts
.TP
.I ints   
.B ntcut
.B =
.R  	 [ncut]
.TP
.I floats 
.B tcut
.B =
.R  	time cuts  [ncut]
.SH SOURCE
.I system/seismic/Mcascade.c
.SH VERSION
4.2
