.TH sfcanny 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfcanny \- Canny-like edge detector. \n.SH SYNOPSIS
.B sfcanny < in.rsf > out.rsf min=5.0 max=95.0
.SH PARAMETERS
.PD 0
.TP
.I float  
.B max
.B =95.0
.R  	maximum threshold
.TP
.I float  
.B min
.B =5.0
.R  	minimum threshold
.SH SOURCE
.I system/generic/Mcanny.c
.SH VERSION
4.2
