.TH sfcausint 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfcausint \- Causal integration on the first axis. \n.SH SYNOPSIS
.B sfcausint < in.rsf > out.rsf adj=n
.SH COMMENTS

December 2013 program of the month:
http://ahay.org/blog/2013/12/01/program-of-the-month-sfcausint/

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	if y, do adjoint integration
.SH SOURCE
.I system/generic/Mcausint.c
.SH VERSION
4.2
