.TH sfcdottest 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfcdottest \- Generic dot-product test for complex linear operators with adjoints \n.SH SYNOPSIS
.B sfcdottest mod=mod.rsf dat=dat.rsf > pip.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dat
.B =
.R  	auxiliary input file name
.TP
.I file   
.B mod
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/main/cdottest.c
.SH VERSION
4.2
