.TH sfcmp2shot 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfcmp2shot \- Convert CMPs to shots for regular 2-D geometry. \n.SH SYNOPSIS
.B sfcmp2shot < in.rsf > out.rsf positive=y
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B positive
.B =y
.R  [y/n]	initial offset orientation
.SH SOURCE
.I system/seismic/Mcmp2shot.c
.SH VERSION
4.2
