.TH sfcmplx 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfcmplx \- Create a complex dataset from its real and imaginary parts.\n.SH SYNOPSIS
.B sfcmplx < real.rsf > cmplx.rsf real.rsf imag.rsf
.SH COMMENTS
There has to be only two input files specified and no additional parameters.

.SH SOURCE
.I system/main/cmplx.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfcmplx
.SH VERSION
4.2
