.TH sfcmatmult2 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfcmatmult2 \- Multiplication of two complex matrices \n.SH SYNOPSIS
.B sfcmatmult2 < in.rsf > out.rsf mat=mat.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B mat
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/generic/Mcmatmult2.c
.SH VERSION
4.2
