.TH sfcostaper 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfcostaper \- Cosine taper around the borders (N-D). \n.SH SYNOPSIS
.B sfcostaper < in.rsf > out.rsf nw#=0
.SH COMMENTS

April 2014 program of the month:
http://ahay.org/blog/2014/04/02/program-of-the-month-sfcostaper/

.SH PARAMETERS
.PD 0
.TP
.I int    
.B nw#
.B =0
.R  	tapering on #-th axis
.SH SOURCE
.I system/generic/Mcostaper.c
.SH VERSION
4.2
