.TH sfcp 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfcp \- Copy or move a dataset.\n.SH SYNOPSIS
.B sfcp < in.rsf > out.rsf in.rsf out.rsf
.SH COMMENTS
sfcp - copy, sfmv - move.
Mimics standard Unix commands.

.SH SOURCE
.I system/main/cp.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfcp
.SH VERSION
4.2
