.TH sfdiffoc 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfdiffoc \- Diffraction focusing test. \n.SH SYNOPSIS
.B sfdiffoc < inp.rsf > out.rsf v0=SF_EPS v= pad=nt pad2=2*kiss_fft_next_fast_size((n2+1)/2) extend=4
.SH PARAMETERS
.PD 0
.TP
.I int    
.B extend
.B =4
.R  	trace extension
.TP
.I int    
.B pad
.B =nt
.R  	padding for stretch
.TP
.I int    
.B pad2
.B =2*kiss_fft_next_fast_size((n2+1)/2)
.R  	padding for FFT
.TP
.I float  
.B v
.B =
.R  	final velocity
.TP
.I float  
.B v0
.B =SF_EPS
.R  	initial velocity
.SH SOURCE
.I system/seismic/Mdiffoc.c
.SH VERSION
4.2
