.TH sfdottest 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfdottest \- Generic dot-product test for linear operators with adjoints \n.SH SYNOPSIS
.B sfdottest mod=mod.rsf dat=dat.rsf > pip.rsf
.SH PARAMETERS
.PD 0
.TP
.I file   
.B dat
.B =
.R  	auxiliary input file name
.TP
.I file   
.B mod
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/main/dottest.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfdottest
.SH VERSION
4.2
