.TH sfdsr 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfdsr \- Prestack 2-D VTI v(z) modeling/migration by DSR with angle gathers. \n.SH SYNOPSIS
.B sfdsr < in.rsf > out.rsf velocity=vel.rsf velz=velz.rsf eta=eta.rsf inv=n eps=0.01 depth=n na=1 da=90. nt= dt= t0=0. nh= dh= nz=nt dz=dt vel= vz=v0 n=0.0 nw=nt2/2+1 rule= arule=
.SH PARAMETERS
.PD 0
.TP
.I string 
.B arule
.B =
.R  	angle gather rule
.TP
.I float  
.B da
.B =90.
.R  	angle sampling (in degrees)
.TP
.I bool   
.B depth
.B =n
.R  [y/n]	if true, depth migration
.TP
.I float  
.B dh
.B =
.R  	Offset sampling (for modeling)
.TP
.I float  
.B dt
.B =
.R  	Sampling of time axis (for modeling)
.TP
.I float  
.B dz
.B =dt
.R  	Sampling of depth axis (for migration, if no velocity file)
.TP
.I float  
.B eps
.B =0.01
.R  	Stabilization parameter
.TP
.I string 
.B eta
.B =
.R  	auxiliary input file name
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	If y, modeling; If n, migration
.TP
.I float  
.B n
.B =0.0
.R  	Constant eta (if no velocity file)
.TP
.I int    
.B na
.B =1
.R  	number of angles
.TP
.I int    
.B nh
.B =
.R  	Number of offsets (for modeling)
.TP
.I int    
.B nt
.B =
.R  	Length of time axis (for modeling)
.TP
.I int    
.B nw
.B =nt2/2+1
.R  	Maximum number of frequencies
.TP
.I int    
.B nz
.B =nt
.R  	Length of depth axis (for migration, if no velocity file)
.TP
.I string 
.B rule
.B =
.R  	phase-shift interpolation rule (simple, midpoint, linear, anisotropic, dti)
.TP
.I float  
.B t0
.B =0.
.R  
.TP
.I float  
.B vel
.B =
.R  	Constant velocity (if no velocity file)
.TP
.I string 
.B velocity
.B =
.R  	file with velocity (file with velocity (auxiliary input file name))
.TP
.I string 
.B velz
.B =
.R  	auxiliary input file name
.TP
.I float  
.B vz
.B =v0
.R  	Constant vertical velocity (if no velocity file)
.SH SOURCE
.I system/seismic/Mdsr.c
.SH VERSION
4.2
