.TH sfenoint2 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfenoint2 \- ENO interpolation in 2-D slices. \n.SH SYNOPSIS
.B sfenoint2 < in.rsf > out.rsf head=head.rsf xkey= ykey= interp=2
.SH PARAMETERS
.PD 0
.TP
.I file   
.B head
.B =
.R  	auxiliary input file name
.TP
.I int    
.B interp
.B =2
.R  	interpolation order
.TP
.I int    
.B xkey
.B =
.R  	x key number
.TP
.I int    
.B ykey
.B =
.R  	y key number
.SH SOURCE
.I system/generic/Menoint2.c
.SH VERSION
4.2 Mbin.c 847 2004-10-27 20:33:16Z fomels
