.TH sffkamo 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsffkamo \- Computes Azimuth Move-Out (AMO) operator in the f-k log-stretch domain \n.SH SYNOPSIS
.B sffkamo < in.rsf > out.rsf h1= h2= f1= f2= maxe=10.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B f1
.B =
.R  	input azimuth in degrees
.TP
.I float  
.B f2
.B =
.R  	output azimuth in degrees
.TP
.I float  
.B h1
.B =
.R  	input offset
.TP
.I float  
.B h2
.B =
.R  	output offset
.TP
.I float  
.B maxe
.B =10.
.R  	stability constraint
.SH SOURCE
.I system/seismic/Mfkamo.c
.SH VERSION
4.2
