.TH sffkdmo 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsffkdmo \- Offset continuation by log-stretch F-K operator. \n.SH SYNOPSIS
.B sffkdmo < in.rsf > out.rsf h= nh=1 h0=0.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B h
.B =
.R  	final offset
.TP
.I float  
.B h0
.B =0.
.R  	initial offset
.TP
.I int    
.B nh
.B =1
.R  	number of offset steps
.SH SOURCE
.I system/seismic/Mfkdmo.c
.SH VERSION
4.2
