.TH sffourvc2 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsffourvc2 \- Velocity continuation with semblance computation. \n.SH SYNOPSIS
.B sffourvc2 < in.rsf > out.rsf nb=2 eps=0.01 pad=n1 pad2=2*kiss_fft_next_fast_size((n2+1)/2) nv= dv= semblance=y extend=4
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dv
.B =
.R  
.TP
.I float  
.B eps
.B =0.01
.R  
.TP
.I int    
.B extend
.B =4
.R  	trace extension
.TP
.I int    
.B nb
.B =2
.R  
.TP
.I int    
.B nv
.B =
.R  
.TP
.I int    
.B pad
.B =n1
.R  
.TP
.I int    
.B pad2
.B =2*kiss_fft_next_fast_size((n2+1)/2)
.R  
.TP
.I bool   
.B semblance
.B =y
.R  [y/n]	if y, compute semblance; if n, stack
.SH SOURCE
.I system/seismic/Mfourvc2.c
.SH VERSION
4.2
