.TH sfget 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfget \- Output parameters from the header.\n.SH SYNOPSIS
.B sfget parform=y all=n par1 par2 ...
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B all
.B =n
.R  [y/n]	If output all values.
.TP
.I bool   
.B parform
.B =y
.R  [y/n]	If y, print out parameter=value. If n, print out value.
.SH SOURCE
.I system/main/get.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfget
.SH VERSION
4.2
