.TH sfgrad3 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfgrad3 \- 3-D smooth gradient. \n.SH SYNOPSIS
.B sfgrad3 < in.rsf > out.rsf dim=0
.SH PARAMETERS
.PD 0
.TP
.I int    
.B dim
.B =0
.R  	dimension of the gradient, 0 for gradient squared
.SH SOURCE
.I system/generic/Mgrad3.c
.SH VERSION
4.2
