.TH sfheat 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfheat \- Finite-difference solution of 2-D heat-flow equation \n.SH SYNOPSIS
.B sfheat > out.rsf impl=n alpha=1.
.SH PARAMETERS
.PD 0
.TP
.I float  
.B alpha
.B =1.
.R  
.TP
.I bool   
.B impl
.B =n
.R  [y/n]	if y, use implicit scheme
.SH SOURCE
.I system/generic/Mheat.c
.SH VERSION
4.2
