.TH sfigrad 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfigrad \- Gradient on the first axis. \n.SH SYNOPSIS
.B sfigrad < in.rsf > out.rsf square=n adj=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.TP
.I bool   
.B square
.B =n
.R  [y/n]	if y, use gradient squared
.SH SOURCE
.I system/generic/Migrad.c
.SH VERSION
4.2
