.TH sfintbin 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfintbin \- Data binning by trace sorting. \n.SH SYNOPSIS
.B sfintbin < in.rsf > out.rsf inv=n xkey= ykey= xmin= xmax= ymin= ymax= head= xk= yk= map= mask=
.SH COMMENTS

If inv=n, the input is 2-D (n1 x ntr). The output is 3-D (n1 x n2 x n3), n2 and
n3 correspond to two selected keys from the header file. 

If inv=y, the input is 3-D, and the output is 2-D.

if xkey < 0, the first axis indexes traces in a gather like cdpt.

June 2015 program of the month:
http://ahay.org/blog/2015/06/10/program-of-the-month-sfintbin/

.SH PARAMETERS
.PD 0
.TP
.I string 
.B head
.B =
.R  	header file
.TP
.I bool   
.B inv
.B =n
.R  [y/n]	inversion flag
.TP
.I string 
.B map
.B =
.R  	output map file
.TP
.I string 
.B mask
.B =
.R  	output mask file
.TP
.I string 
.B xk
.B =
.R  	x key name
.TP
.I int    
.B xkey
.B =
.R  	x key number (if no xk), default is fldr
.TP
.I int    
.B xmax
.B =
.R  	x maximum
.TP
.I int    
.B xmin
.B =
.R  	x minimum
.TP
.I string 
.B yk
.B =
.R  	y key name
.TP
.I int    
.B ykey
.B =
.R  	y key number (if no yk), default is tracf
.TP
.I int    
.B ymax
.B =
.R  	y maximum
.TP
.I int    
.B ymin
.B =
.R  	y minimum
.SH SOURCE
.I system/seismic/Mintbin.c
.SH VERSION
4.2
