.TH sfinterleave 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfinterleave \- Combine several datasets by interleaving.\n.SH SYNOPSIS
.B sfinterleave > out.rsf axis=3 [< file0.rsf] file1.rsf file2.rsf ...
.SH PARAMETERS
.PD 0
.TP
.I int    
.B axis
.B =3
.R  	Axis for interleaving
.SH SOURCE
.I system/main/interleave.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfinterleave
.SH VERSION
4.2
