.TH sfjacobi 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfjacobi \- Find eigenvalues of a symmetric matrix by Jacobi's iteration. \n.SH SYNOPSIS
.B sfjacobi < mat.rsf > val.rsf eig=eig.rsf niter=10
.SH PARAMETERS
.PD 0
.TP
.I string 
.B eig
.B =
.R  	auxiliary output file name
.TP
.I int    
.B niter
.B =10
.R  
.SH SOURCE
.I system/generic/Mjacobi.c
.SH VERSION
4.2
