.TH sflaplac 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsflaplac \- 2-D finite-difference Laplacian operation. \n.SH SYNOPSIS
.B sflaplac < in.rsf > out.rsf adj=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]	adjoint flag
.SH SOURCE
.I system/generic/Mlaplac.c
.SH VERSION
4.2
