.TH sflinefit 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsflinefit \- Fit a line to a set of points in 2-D.\n.SH SYNOPSIS
.B sflinefit < in.rsf > out.rsf pattern=pattern.rsf
.SH PARAMETERS
.PD 0
.TP
.I string 
.B pattern
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/generic/Mlinefit.c
.SH VERSION
4.2
