.TH sfmatmult 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfmatmult \- Simple matrix multiplication \n.SH SYNOPSIS
.B sfmatmult < in.rsf > out.rsf mat=mat.rsf adj=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]
.TP
.I file   
.B mat
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/generic/Mmatmult.c
.SH VERSION
4.2
