.TH sfmodrefl2 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfmodrefl2 \- Normal reflectivity modeling. \n.SH SYNOPSIS
.B sfmodrefl2 < in.rsf > out.rsf nt= dt= nw=4
.SH COMMENTS

In this version, the input contains Vp, Vs, and density into one file. 
The output contains PP intercept, PP gradient, and PS gradient.


.SH PARAMETERS
.PD 0
.TP
.I float  
.B dt
.B =
.R  	time sampling
.TP
.I int    
.B nt
.B =
.R  	time samples
.TP
.I int    
.B nw
.B =4
.R  	interpolation length
.SH SOURCE
.I system/seismic/Mmodrefl2.c
.SH VERSION
4.2
