.TH sfmpi 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfmpi \- MPI wrapper for embarassingly parallel jobs. \n.SH SYNOPSIS
.B sfmpi split=ndim join=axis
.SH PARAMETERS
.PD 0
.TP
.I int    
.B join
.B =axis
.R  	axis to join (0 means add)
.TP
.I int    
.B split
.B =ndim
.R  	axis to split
.SH SOURCE
.I system/main/mpi.c
.SH VERSION
4.2
