.TH sfnmow_adj 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfnmow_adj \- None\n.SH SYNOPSIS
.B sfnmow_adj < inp.rsf > out.rsf gather=gather.rsf adj=n nw=3
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B adj
.B =n
.R  [y/n]
.TP
.I file   
.B gather
.B =
.R  	auxiliary input file name
.TP
.I int    
.B nw
.B =3
.R  
.SH SOURCE
.I system/seismic/Mnmow_adj.c
.SH VERSION
4.2
