.TH sfpow 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfpow \- Apply power gain. \n.SH SYNOPSIS
.B sfpow < in.rsf > out.rsf tpow= pow#=(0,0,...)
.SH COMMENTS

March 2013 program of the month:
http://www.ahay.org/blog/2013/03/10/program-of-the-month-sfpow/

.SH PARAMETERS
.PD 0
.TP
.I float  
.B pow#
.B =(0,0,...)
.R  	power on #-th axis
.TP
.I float  
.B tpow
.B =
.R  
.SH SOURCE
.I system/generic/Mpow.c
.SH VERSION
4.2
