.TH sfput 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfput \- Input parameters into a header. \n.SH SYNOPSIS
.B sfput < in.rsf > out.rsf [parameter=value list]
.SH SOURCE
.I system/main/put.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfput
.SH VERSION
4.2
