.TH sfreal 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfreal \- Extract real (sfreal) or imaginary (sfimag) part of a complex dataset. \n.SH SYNOPSIS
.B sfreal < cmplx.rsf > real.rsf
.SH SOURCE
.I system/main/real.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfreal
.SH VERSION
4.2
