.TH sfrm 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfrm \- Remove RSF files together with their data.\n.SH SYNOPSIS
.B sfrm file1.rsf [file2.rsf ...] [-i] [-v] [-f] 
.SH COMMENTS
Mimics the standard Unix rm command.

See also: sfmv, sfcp.

.SH SOURCE
.I system/main/rm.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfrm
.SH VERSION
4.2
