.TH sfrtoc 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfrtoc \- Convert real data to complex (by adding zero imaginary part).\n.SH SYNOPSIS
.B sfrtoc < real.rsf > cmplx.rsf pair=n
.SH COMMENTS

See also: sfcmplx

.SH PARAMETERS
.PD 0
.TP
.I bool   
.B pair
.B =n
.R  [y/n]	y - use odd elements for real part and even ones for imaginary part
.SH SOURCE
.I system/main/rtoc.c
.SH DOCUMENTATION
.BR http://ahay.org/wiki/Guide_to_madagascar_programs#sfrtoc
.SH VERSION
4.2
