.TH sfshotholes 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfshotholes \- Remove random shot gathers from a 2-D dataset. \n.SH SYNOPSIS
.B sfshotholes < in.rsf > mask.rsf perc=0.75
.SH PARAMETERS
.PD 0
.TP
.I float  
.B perc
.B =0.75
.R  	how many shots to remove
.SH SOURCE
.I system/seismic/Mshotholes.c
.SH VERSION
4.2
