.TH sfsinc 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfsinc \- 1-D sinc interpolation.\n.SH SYNOPSIS
.B sfsinc < in.rsf > out.rsf pattern=pattern.rsf
.SH COMMENTS

Specify either n1= o1= d1= or pattern=

.SH PARAMETERS
.PD 0
.TP
.I string 
.B pattern
.B =
.R  	auxiliary input file name
.SH SOURCE
.I su/main/sinc.c
.SH VERSION
4.2
