.TH sfslice 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfslice \- Extract a slice using picked surface (usually from a stack or a semblance).\n.SH SYNOPSIS
.B sfslice < in.rsf pick=pick.rsf > out.rsf
.SH COMMENTS

See also: sfpick.

June 2019 program of the month:
http://ahay.org/blog/2019/06/12/program-of-the-month-sfslice/

.SH PARAMETERS
.PD 0
.TP
.I file   
.B pick
.B =
.R  	auxiliary input file name
.SH SOURCE
.I system/generic/Mslice.c
.SH VERSION
4.2
