.TH sfsmoothreg2 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfsmoothreg2 \- Smoothing in 2-D by simple regularization.\n.SH SYNOPSIS
.B sfsmoothreg2 < in.rsf > smooth.rsf eps=1. repeat=1
.SH PARAMETERS
.PD 0
.TP
.I float  
.B eps
.B =1.
.R  	smoothness parameter
.TP
.I int    
.B repeat
.B =1
.R  	repeat smoothing
.SH SOURCE
.I system/generic/Msmoothreg2.c
.SH VERSION
4.2
