.TH sfsplinefilter 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfsplinefilter \- Convert data to B-spline coefficients. \n.SH SYNOPSIS
.B sfsplinefilter < in.rsf > out.rsf nw=
.SH PARAMETERS
.PD 0
.TP
.I int    
.B nw
.B =
.R  	filter size
.SH SOURCE
.I system/generic/Msplinefilter.c
.SH VERSION
4.2
