.TH sfspectra2 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfspectra2 \- Frequency spectra in 2-D. \n.SH SYNOPSIS
.B sfspectra2 < in.rsf > out.rsf all=n
.SH PARAMETERS
.PD 0
.TP
.I bool   
.B all
.B =n
.R  [y/n]	if y, compute average spectrum for all traces
.SH SOURCE
.I system/generic/Mspectra2.c
.SH VERSION
4.2
