.TH sfthreshold 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfthreshold \- Soft thresholding. \n.SH SYNOPSIS
.B sfthreshold < in.rsf > out.rsf pclip=
.SH COMMENTS

November 2014 program of the month:
http://ahay.org/blog/2014/11/12/program-of-the-month-sfthreshold/

.SH PARAMETERS
.PD 0
.TP
.I float  
.B pclip
.B =
.R  	percentage to clip
.SH SOURCE
.I system/generic/Mthreshold.c
.SH VERSION
4.2
