.TH sfvczo3 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfvczo3 \- Post-stack 3-D velocity continuation. \n.SH SYNOPSIS
.B sfvczo3 < in.rsf > out.rsf eps=0.01 pad=n1 pad2=2*kiss_fft_next_fast_size((n2+1)/2) verb=y nv= dv= v0=
.SH PARAMETERS
.PD 0
.TP
.I float  
.B dv
.B =
.R  	velocity step size
.TP
.I float  
.B eps
.B =0.01
.R  	regularization
.TP
.I int    
.B nv
.B =
.R  	velocity steps
.TP
.I int    
.B pad
.B =n1
.R  	padding for stretch
.TP
.I int    
.B pad2
.B =2*kiss_fft_next_fast_size((n2+1)/2)
.R  	padding for FFT
.TP
.I float  
.B v0
.B =
.R  	starting velocity
.TP
.I bool   
.B verb
.B =y
.R  [y/n]	verbosity flag
.SH SOURCE
.I system/seismic/Mvczo3.c
.SH VERSION
4.2
