.TH sfvoft 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nsfvoft \- V(t) function for a linear V(Z) profile.\n.SH SYNOPSIS
.B sfvoft < in.rsf > out.rsf v0=1.5 alpha=0.5
.SH PARAMETERS
.PD 0
.TP
.I float  
.B alpha
.B =0.5
.R  	velocity gradient
.TP
.I float  
.B v0
.B =1.5
.R  	initial velocity
.SH SOURCE
.I system/seismic/Mvoft.c
.SH VERSION
4.2
