.TH vp7ab 1  "DECEMBER 2025" Madagascar "Madagascar Manuals"
.SH NAME\nvp7ab \- \n.SH SYNOPSIS
.B vp7ab c=c.rsf d=d.rsf > plot.vpl top=5. c1=0.5 c2=5.
.SH PARAMETERS
.PD 0
.TP
.I string 
.B c
.B =
.R  	auxiliary output file name
.TP
.I float  
.B c1
.B =0.5
.R  
.TP
.I float  
.B c2
.B =5.
.R  
.TP
.I string 
.B d
.B =
.R  	auxiliary output file name
.TP
.I float  
.B top
.B =5.
.R  
.SH SOURCE
.I plot/test/7ab.c
.SH VERSION
4.2
